# Input
twist_topic: cmd_delta
joint_state_topic: quince_arm/joint_states
# Output
traj_topic: quince_arm/controller/command
move_group_name: arm
planning_frame_id: world
stale_limit: 0.25
publish_rate: 10
trajectory:
  duration: 0.1
  resolution: 0.1
thresholds:
  slow_down: 12
  hard_stop: 20
