# Input
twist_topic: cmd_delta
joint_state_topic: quince_arm/joint_states
# Output
traj_topic: quince_arm/controller/command
move_group_name: arm
planning_frame_id: world
stale_limit: 0.25
# Divergence tolerance in meters
joint_state_divergence: 0.1
publish_rate: 5
trajectory:
  duration: 0.2
  resolution: 0.2
thresholds:
  # If 0, uses the maximum speed used by MoveIt!
  max_speed: 0.3
singularity:
  slow_down:
    cn: 10
    multiplier: 0.3
  hard_stop:
    cn: 20
    multiplier: 0.1
